language: python
python:
- '3.6'
install:
- pip install -r ./requirements.txt
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: RPSpqfeRGeiyKUxqSxXA1kFGBJiO9N4bgbpAachB2xTbZu5c6QDjBYn5GK+qLet9QJIJs5s8jAU+Juj/ip6OoSiOkRG4ZLq/T9uCy8vYxnB3UVgShSZbcTlmL0kFxT89qefw2Hv+txsc5SBxS8+AjR92oq1Nk8C1wPhiSfqN4Dpbe8tFGdgoqMx/RnhiDq6SmiI8bA3G0jN5ecXE5kF5pFFAYtWceWmiYjjKWywwcn/Ckf102AS/rHAEW6T+ldlojFsUrEC+OEJMsz7eqjhIuYjXQvFY+2878aqAgPhIu94C9V1HISC6pQpwSwvfNz0Ff4h6W5VvWKKgEp9+O7E/nVPsxx2v6mEUyiRBoGGjEQPyWMMbEyMRHdSchrKeEBnQW3ph6CXxE6qEfw1MpbrCeKC8pIDyoN9cH/NnUGnyzlh2B1pJQsPDZ6jmkGZhziXRof36oWwOXOkV6RzAkPq1U5fOgg6Om4ClrMim7/7QfecQqwhKKDxFd3tNcNcAJUtXMIsncXI1tEXne0tfqXKgtAunU30U9FwpBOex+Lqo073QyUNLrDjj3nPIvJ/LfUvgTwFG19Ok1SEIKyeiw7Gc9y5eYMk+13MCZJwGPVK85m95ECjFg4N5Qh7LHxky75rR3XAg4lyB9wV9zRovZjui+19pHtKY7siXv7H/fvfaHs0=
  - secure: fzKp1ekm43nIcOPuVfPIwyAdu3DER0D23Z8GzWFeUHZiH403t0RxPtLPU61ckhCih72r8FlnrNm8JjGh11NgJ35TDsfDK5GY1I+4u08eUjFSd7o9JG08ifPaWKn/w/puYr3zJ5tEhYC05Q2SNQE4UsvpNZhXf0L4+AT+qpbhX2d523vvBm4ONQC4bfbJtP02KvNSBUhIkokZtqwKdphwFLFROZC5jP6D0D93fpOEpsK5Z2H2ynkO7+8hYKc6KbYkRTQ3ypBFIBmJv+iP2Po2z87HVDQglWXjUzb3lMRmIpLR+Co2PMhIJ4wjRI6zDNrRqNp2zJbmWY0XlJW0WIxYYRdIqgtzCFzZmKEn8Dlr5uqekmqR3DnfQfISTCJQ0/q93kSxfQDosgAaviiyzDuFmacBoYdQjUGHMIBo9gopANAaVxnx8ORINLc/cHFakbZ3yEyiIS8x8rdr+yzTvOP0a+Ehh7kMgrp+OB6+eGj7YQbe7eu4RwIwJgGS3dObbCx70lkO/02SZyWky3QpU6eHcJ7eWoX+zAvPqt+70Jm4baQh2GPke0nzqELU2rksochNjXc8q847rizUwSYLq7QIdp65wdQ2K2w/e8y3ziByr3k1Q7YSUJzdqOerqvayM7zI6IFcZpMdhs2vpBVCn57DBy0xpE4n1a8uXTCJiBM7QHI=
  - secure: KjyBICE4kFrzXUUUnBOGu3fGbplnXGLWzEczOMSGaNsK15qEzmT4GQuwPt5zDwktge20A5vPcKRn/MfJ7dqRz7JtrOECbC3m2JQRzoYZjCrTTcTLpFvbPH30ZCfk3BdfNJ7f5GSzp2tYMCszGF/LkJ29rBCvxaN4baVRoB9JsRBJ50U9ydWpch8YAx88T5mgjQugwaWViXj6BIoGj+zmI6QtDj/5LTIWq7i3iNCRiH0OE3zyZf/k6E5uT2cdS/PsvReZnpdalxs3vQYqo3e/HcRnxySkjPmktHRv+M61K83PbJWfdSNoRtXA0EJYwBki6K9xpOQw2weYxtX0oQIoJkf07ChqK3vkVUgwpf8sKXU0lkK+88t13tQyXRXGJ+VY6evbZ3wm95wfegXTRIi3ttvAPspYHP9T+Aa5fHbbNhxMrBRYZlmEdT2wozpMTY9JlE/+3yumOWCFibQYWbzFabgihil4RiE7A0h+fmu+epEP78HiIOjytUzv3b5yfK108JsoIF6Sdsbpfn4t0oKIjVHjhJxyHiYhIVLdSKQAV2BC41BVFzr8QPXT0iwd2uYTG9n2hMmEh5KrUjJMj3PjkYaEYPI3WkTGGSJF1IdUVYfMOCFNy8dN+eIiBPmmKdQKfQwHTQzxYUBrmnlj/4lAASTTM15lR2idmxGaKZmNdW4=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv travis /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/travis
